=== jakegude/DMACC-Projects/My Access Files/Access Database Files/Unit P/NewPlayers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="tblPlayers" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="tblPlayers">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="Number" index-key="PlayerNo " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="PlayerNo " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="0"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAAucQheUfvSEZw0ABlPwQANAAAAANQeMIR8tuFAAAAAAAAAAABQAGwA
YQB5AGUAcgBzAAAAAAAAAC9xCF5R+9IRnDQAGU/BAA0HAAAALnEIXlH70hGcNAAZ
T8EADUYAaQByAHMAdAAAAAAAAAAwcQheUfvSEZw0ABlPwQANBwAAAC5xCF5R+9IR
nDQAGU/BAA1MAGEAcwB0AAAAAAAAADFxCF5R+9IRnDQAGU/BAA0HAAAALnEIXlH7
0hGcNAAZT8EADUgAZQBpAGcAaAB0AAAAAAAAADJxCF5R+9IRnDQAGU/BAA0HAAAA
LnEIXlH70hGcNAAZT8EADVAAbABhAHkAZQByAE4AbwAAAAAAAABKcQheUfvSEZw0
ABlPwQANBwAAAC5xCF5R+9IRnDQAGU/BAA1ZAGUAYQByAAAAAAAAAEtxCF5R+9IR
nDQAGU/BAA0HAAAALnEIXlH70hGcNAAZT8EADVAAbwBzAGkAdABpAG8AbgAAAAAA
AAA5cQheUfvSEZw0ABlPwQANBwAAAC5xCF5R+9IRnDQAGU/BAA1IAG8AbQBlAFQA
bwB3AG4AAAAAAAAATHEIXlH70hGcNAAZT8EADQcAAAAucQheUfvSEZw0ABlPwQAN
SABvAG0AZQBTAHQAYQB0AGUAAAA=
"/>
<od:tableProperty name="GUID" type="9" value="LnEIXlH70hGcNAAZT8EADQ==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="100"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="-1"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="FirstName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="L3EIXlH70hGcNAAZT8EADQ==
"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="LastName" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="MHEIXlH70hGcNAAZT8EADQ==
"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Height" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Height in inches"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="MXEIXlH70hGcNAAZT8EADQ==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="PlayerNo" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="GUID" type="9" value="MnEIXlH70hGcNAAZT8EADQ==
"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="YearInSchool" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="ValidationRule" type="12" value="&quot;Fr&quot; Or &quot;So&quot; Or &quot;Jr&quot; Or &quot;Sr&quot;"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="SnEIXlH70hGcNAAZT8EADQ==
"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="2"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="Position" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="ValidationRule" type="12" value="&quot;C&quot; Or &quot;F&quot; Or &quot;G&quot;"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="S3EIXlH70hGcNAAZT8EADQ==
"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="1"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="HomeTown" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="OXEIXlH70hGcNAAZT8EADQ==
"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="50"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="HomeState" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="GUID" type="9" value="THEIXlH70hGcNAAZT8EADQ==
"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="2"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>

=== jakegude/DMACC-Projects/My Access Files/Access Database Files/Unit P/NewPlayers.xml
<?xml version="1.0" encoding="UTF-8"?>
<dataroot xmlns:od="urn:schemas-microsoft-com:officedata" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="NewPlayers.xsd" generated="2013-04-07T07:59:17">
<tblPlayers>
<FirstName>Sandy</FirstName>
<LastName>Franklin</LastName>
<Height>62</Height>
<PlayerNo>4</PlayerNo>
<YearInSchool>Fr</YearInSchool>
<Position>G</Position>
<HomeTown>Des Moines</HomeTown>
<HomeState>IA</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Lori</FirstName>
<LastName>Sandereson</LastName>
<Height>67</Height>
<PlayerNo>5</PlayerNo>
<YearInSchool>Fr</YearInSchool>
<Position>G</Position>
<HomeTown>West Des Moines</HomeTown>
<HomeState>IA</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Ellen</FirstName>
<LastName>Harding</LastName>
<Height>69</Height>
<PlayerNo>12</PlayerNo>
<YearInSchool>Fr</YearInSchool>
<Position>G</Position>
<HomeTown>Minnetonka</HomeTown>
<HomeState>MN</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Allison</FirstName>
<LastName>Harris</LastName>
<Height>70</Height>
<PlayerNo>21</PlayerNo>
<YearInSchool>Fr</YearInSchool>
<Position>F</Position>
<HomeTown>Springfield</HomeTown>
<HomeState>IL</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Terry</FirstName>
<LastName>Garfield</LastName>
<Height>70</Height>
<PlayerNo>22</PlayerNo>
<YearInSchool>Fr</YearInSchool>
<Position>F</Position>
<HomeTown>Dallas</HomeTown>
<HomeState>TX</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Sara</FirstName>
<LastName>Richards</LastName>
<Height>60</Height>
<PlayerNo>23</PlayerNo>
<YearInSchool>So</YearInSchool>
<Position>G</Position>
<HomeTown>Bridgewater</HomeTown>
<HomeState>IA</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Amy</FirstName>
<LastName>Scallia</LastName>
<Height>70</Height>
<PlayerNo>30</PlayerNo>
<YearInSchool>Fr</YearInSchool>
<Position>F</Position>
<HomeTown>Manhattan</HomeTown>
<HomeState>KS</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Ashley</FirstName>
<LastName>Welker</LastName>
<Height>73</Height>
<PlayerNo>32</PlayerNo>
<YearInSchool>So</YearInSchool>
<Position>C</Position>
<HomeTown>Minot</HomeTown>
<HomeState>ND</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Kayla</FirstName>
<LastName>Carter</LastName>
<Height>73</Height>
<PlayerNo>35</PlayerNo>
<YearInSchool>So</YearInSchool>
<Position>F</Position>
<HomeTown>Lincoln</HomeTown>
<HomeState>NE</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Diane</FirstName>
<LastName>Farmingham</LastName>
<Height>70</Height>
<PlayerNo>42</PlayerNo>
<YearInSchool>Jr</YearInSchool>
<Position>F</Position>
<HomeTown>Madison</HomeTown>
<HomeState>WI</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Martha</FirstName>
<LastName>Howison</LastName>
<Height>74</Height>
<PlayerNo>45</PlayerNo>
<YearInSchool>Jr</YearInSchool>
<Position>F</Position>
<HomeTown>Greenfield</HomeTown>
<HomeState>IA</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Mary</FirstName>
<LastName>Thomas</LastName>
<Height>71</Height>
<PlayerNo>51</PlayerNo>
<YearInSchool>So</YearInSchool>
<Position>G</Position>
<HomeTown>Cherokee</HomeTown>
<HomeState>MN</HomeState>
</tblPlayers>
<tblPlayers>
<FirstName>Judy</FirstName>
<LastName>Jacobson</LastName>
<Height>75</Height>
<PlayerNo>52</PlayerNo>
<YearInSchool>Fr</YearInSchool>
<Position>F</Position>
<HomeTown>Fontanelle</HomeTown>
<HomeState>IL</HomeState>
</tblPlayers>
</dataroot>
